# Optional support for GDCompanion development: https://ko-fi.com/bunnibranch
ko_fi: bunnibranch
# Setup and supported keys:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
